### ISSUE TITLE
SongNotPassIntegrityCheckException

### ISSUE THREAD

**Issue by Gonimbrasia** [WorldObservationLog/AppleMusicDecrypt#20]
How can I correct this error? :-

```
2024-06-13 16:39:55.616 | INFO     | src.cmd:__init__:70 - Device 127.0.0.1:5555 has connected
> download https://music.apple.com/gb/album/let-somebody-go-ofenbach-remix-single/1618673344
2024-06-13 16:40:34.180 | INFO     | src.rip:rip_album:133 - Ripping Album: Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix) - Single
2024-06-13 16:40:34.434 | INFO     | src.rip:rip_song:39 - Ripping song: Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix)
2024-06-13 16:40:41.291 | INFO     | src.rip:rip_song:81 - Use m3u8 from device for song: Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix)
2024-06-13 16:40:41.526 | INFO     | src.mp4:extract_media:51 - Selected codec: audio-alac-stereo-44100-24 for song: Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix)
2024-06-13 16:40:41.607 | INFO     | src.rip:rip_song:94 - Downloading song: Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix)
2024-06-13 16:41:39.621 | INFO     | src.decrypt:decrypt:25 - Using device 127.0.0.1:5555 to decrypt song: Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix)
2024-06-13 16:41:44.180 | WARNING  | src.rip:rip_song:117 - Song Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix) did not pass the integrity check!
2024-06-13 16:41:44.180 | ERROR    | __main__:<module>:16 - An error has been caught in function '<module>', process 'MainProcess' (4392), thread 'MainThread' (844):
Traceback (most recent call last):

  File "D:\Programs\AppleMusicDecrypt\tenacity\_asyncio.py", line 61, in __call__

  File "D:\Programs\AppleMusicDecrypt\src\rip.py", line 118, in rip_song

src.exceptions.SongNotPassIntegrityCheckException


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "D:\Programs\AppleMusicDecrypt\main.py", line 16, in <module>

  File "D:\Programs\AppleMusicDecrypt\src\utils.py", line 74, in helper

  File "D:\Programs\AppleMusicDecrypt\src\utils.py", line 68, in process

  File "D:\Programs\AppleMusicDecrypt\tenacity\_asyncio.py", line 142, in async_wrapped

  File "D:\Programs\AppleMusicDecrypt\tenacity\_asyncio.py", line 58, in __call__

  File "D:\Programs\AppleMusicDecrypt\tenacity\_asyncio.py", line 110, in iter

  File "D:\Programs\AppleMusicDecrypt\tenacity\_asyncio.py", line 78, in inner

  File "D:\Programs\AppleMusicDecrypt\tenacity\__init__.py", line 411, in exc_check

tenacity.RetryError: RetryError[<Future at 0x217b8a4f5d0 state=finished raised SongNotPassIntegrityCheckException>]
2024-06-13 16:41:44.188 | INFO     | src.rip:rip_album:145 - Album: Coldplay & Selena Gomez - Let Somebody Go (Ofenbach Remix) - Single finished ripping
```

**Comment by WorldObservationLog** [comment]
This is an expected error, and is intended to prevent the script from saving corrupted audio files (files where the last tens or even minutes of audio cannot be decoded). Restarting the emulator should fix the problem.

**Comment by WorldObservationLog** [comment]
Since this is a problem with the Apple Music client (it can be reproduced in versions 3.6.0-beta and 4.8.0-beta, whether decrypting or listening to music normally), we can only provide a temporary solution for this problem.

**Comment by Gonimbrasia** [comment]
Restarting the emulator doesn't fix the problem no matter how many times I do it. Although the file is downloading, it doesn't seem to be saved anywhere. No download directory is created.

**Comment by WorldObservationLog** [comment]
> Restarting the emulator doesn't fix the problem no matter how many times I do it. Although the file is downloading, it doesn't seem to be saved anywhere. No download directory is created.

Try these follow steps and see if the problem solved:
- Restart the Android emulator
- Clear the data of Apple Music and re-login
- Remove the emulator and create a new one

**Comment by Gonimbrasia** [comment]
Thanks but none of the suggestions above have worked. I've deleted the original emulator and created a new one with a different brand of phone. The same error occurs. I can use zhaarey's apple-music-alac-atmos-downloader without a problem using this setup and the previous one, so I don't understand why there should be a problem with AppleMusicDecrypt.
I will leave it for now and maybe try again at some point in the future with a newer build, unless you have any other suggestions.
