### ISSUE TITLE
Test instance unstable

### ISSUE THREAD

**Issue by StormProductionsMusic** [WorldObservationLog/AppleMusicDecrypt#61]
Hi,

Seems like the test instance included with the Windows pre-made version (wm.wol.moe) is absolutely not working for 3 days already, throwing the following error:

```
2025-10-04 13:03:53.845 | WARNING - Retrying src.grpc.manager.WrapperManager.lyrics in 0.7397298878592755 seconds as it raised WrapperManagerException: Get "https://beta.music.apple.com": dial tcp: lookup beta.music.apple.com on 127.0.0.11:53: read udp 127.0.0.1:33560->127.0.0.11:53: i/o timeout.
```

Can you please give me a list of where can I get other public instances?  Unfortunately I'm not taht tech savvy to set up my own.

Thanks!

**Comment by Vehnum** [comment]
I was getting this same error before going and just setting up the self-hosted wrapper and the wrapper manager using WSL and docker.

Here are some of the commands that helped me get it to work


Wrapper:
`/AppleMusicDecrypt/Wrapper.x86_64.d0d9eb2 sudo ./wrapper -H 0.0.0.0 -L username:password` (insert your username and password there)

Wrapper-manager:
`/AppleMusicDecrypt/wrapper-manager docker compose up`


Decrypt: 
`/AppleMusicDecrypt/AppleMusicDecrypt poetry run python tools/login.py`
 `/AppleMusicDecrypt/AppleMusicDecrypt poetry run python main.py`

don't forget this:

```
cd AppleMusicDecrypt
bash ./tools/install-deps.sh
poetry install
cp config.example.toml config.toml
poetry run python main.py
```

had to install poetry as well, "poetry install" would not work


edit: just read the last line on your message, I'm sure this might help someone else.

**Comment by StormProductionsMusic** [comment]
I know about this, however I don't have neither the knowledge nor so many phone numbers to keep creating Apple Music trials.  So in short, I don't have an Apple Music subscription, so i can only use public instances.

**Comment by Vehnum** [comment]
> I know about this, however I don't have neither the knowledge nor so many phone numbers to keep creating Apple Music trials. So in short, I don't have an Apple Music subscription, so i can only use public instances.

Yeah i just edited my reply i didn't see the last line of your post.

If you really wanted to, this would work as a temp fix for you If you were able to set it up with a single Apple Music trial until they fix the Windows pre-made-version.

**Comment by StormProductionsMusic** [comment]
> Yeah i just edited my reply i didn't see the last line of your post.

Don't you know about other running public instances or places I can check for them?  The included one is still not fixed and I can't find a propper way to download from AM right now.

**Comment by Vehnum** [comment]
> > Yeah i just edited my reply i didn't see the last line of your post.
> 
> Don't you know about other running public instances or places I can check for them? The included one is still not fixed and I can't find a propper way to download from AM right now.

I’m sorry I don’t know of any other one.

**Comment by WorldObservationLog** [comment]
fixed

**Comment by StormProductionsMusic** [comment]
Still not downloading:

```
D:\Downloads\AppleMusicDecrypt-Windows>set PATH=D:\Downloads\AppleMusicDecrypt-Windows\deps;   && .venv\python.exe main.py
2025-10-07 15:31:55.844 | INFO - Regions available on wrapper-manager instance: MT, GB, ID, US, IN, CN, BR, JP, AU, NZ
> dl https://music.apple.com/us/song/undeva-%C3%AEn-balkani-feat-george-hora-screen-remix/1578503294
2025-10-07 15:32:14.063 | SONG | Puya - Undeva în Balkani (feat. George Hora) [ScreeN Remix] | INFO - Start ripping...
2025-10-07 15:32:20.048 | WARNING - Retrying src.grpc.manager.WrapperManager.m3u8 in 0.6431057741505798 seconds as it raised WrapperManagerException: failed to get m3u8 of adamId: 1578503294.
2025-10-07 15:32:26.870 | WARNING - Retrying src.api.WebAPI._request in 0.10383490405402795 seconds as it raised ReadTimeout: .
2025-10-07 15:32:32.031 | WARNING - Retrying src.api.WebAPI._request in 0.9812105216049831 seconds as it raised ReadTimeout: .
2025-10-07 15:32:38.075 | WARNING - Retrying src.api.WebAPI._request in 3.2219267509945597 seconds as it raised ReadTimeout: .

```

Do I need to download another version of the thing?  Thanks!

**Comment by harync** [comment]
Is there a way to enable using my own apple music account with the Windows pre-made version?

**Comment by StormProductionsMusic** [comment]
> Is there a way to enable using my own apple music account with the Windows pre-made version?

Yes, use the `login` command, then it will ask you for username (which is the email), then the password.
